let chess = {
    idClassName: 'figura2',
    classBP: 'peshkaB',
    urlBPeshka: "url('img/IBP.png')",
    classBL: 'ladB',
    urlBLad: "url('img/IBL.png')",
    classBH: 'horseB',
    urlBHorse: "url('img/IBK.png')",
    classBC: 'clonB',
    urlBClon: "url('img/IBC.png')",
    classBF: 'ferzB',
    urlBFerz: "url('img/IBF.png')",
    classBKr: 'kingB',
    urlBKing: "url('img/IBKr.png')",
    classWP: 'peshkaW',
    urlWPeshka: "url('img/IWP.png')",
    classWL: 'ladW',
    urlWLad: "url('img/IWL.png')",
    classWH: 'horseW',
    urlWHorse: "url('img/IWK.png')",
    classWC: 'clonW',
    urlWClon: "url('img/IWC.png')",
    classWF: 'ferzW',
    urlWFerz: "url('img/IWF.png')",
    classWKr: 'kingW',
    urlWKing: "url('img/IWKr.png')"
};